# Standards: 0.1
---
- name: Fact mattermost user
  set_fact:
    mattermost_user: "{{ mattermost_user | default(homebrew_user) | default(ansible_user_id) }}"
  tags:
    - mattermost

- become: "{{ (mattermost_user != ansible_user_id) | bool }}"
  become_user: "{{ mattermost_user }}"
  block:
    - name: Install required package
      ignore_errors: True
      homebrew_cask:
        name: mattermost
        greedy: True
        options: appdir=/Applications
        accept_external_apps: False
        state: upgraded
      tags:
        - mattermost

- name: Remove quarantine flag
  register: mattermost_quarantine
  failed_when: mattermost_quarantine.rc != 0 and "No such xattr" not in mattermost_quarantine.stderr
  changed_when: mattermost_quarantine.rc == 0
  command: xattr -d com.apple.quarantine /Applications/Mattermost.app
  tags:
    - mattermost

...
