# Standards: 0.1
---
- name: Kill mattermost
  command: killall Mattermost
  register: mattermost_kill
  failed_when: mattermost_kill.rc != 0 and "No matching processes belonging to you were found" not in mattermost_kill.stderr
  become: "{{ (mattermost_user != ansible_user_id) | bool }}"
  become_user: "{{ mattermost_user }}"

- name: Start mattermost
  when: mattermost_started
  command: open -j /Applications/Mattermost.app
  become: "{{ (mattermost_user != ansible_user_id) | bool }}"
  become_user: "{{ mattermost_user }}"

...
